# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "sinatra", "~> 4.1.1"
gem "sinatra-contrib", "~> 4.1.1"
gem "rack", "~> 3.2.1"
gem "rack-session", "~> 2.1.1"
gem "sequel"
gem "sqlite3"
gem "colorize"
gem "jwt"
gem "webrick", "~> 1.9.1"
gem "rackup"